In [3]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sqlite3
import random
import string

# the number of players: 30
LETTERS = string.ascii_letters

def get_random_string(num: int) -> str:
    random_letters = random.choices(LETTERS, k=num)
    return ''.join(random_letters)

dbname = 'cit-db-2025-game.db'
conn = sqlite3.connect(dbname)
cur = conn.cursor()

# --- playerテーブル再作成 ---
cur.execute("DROP TABLE IF EXISTS player;")
cur.execute("""
CREATE TABLE player (
    player_id INTEGER PRIMARY KEY,
    fname      VARCHAR(20) NOT NULL,
    lname      VARCHAR(20) NOT NULL,
    points     INTEGER     NOT NULL,
    rank       VARCHAR(1)  NOT NULL
);
""")

# --- データ投入 ---
for number in range(30):
    fname = get_random_string(5)
    lname = get_random_string(5)
    rank  = ''.join(random.choices(string.ascii_uppercase, k=1))
    points = random.randrange(1, 100)

    cur.execute(
        "INSERT INTO player (player_id, fname, lname, points, rank) VALUES (?, ?, ?, ?, ?)",
        (number, fname, lname, points, rank)
    )

conn.commit()

# --- テーブル一覧表示 ---
print("\n=== Tables ===")
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cur.fetchall()
for table in tables:
    print(table[0])

# --- カラム一覧表示 ---
for table in tables:
    t = table[0]
    print(f"\n=== Columns in {t} ===")
    cur.execute(f"PRAGMA table_info({t});")
    for col in cur.fetchall():
        print(f"{col[1]} ({col[2]})")

# --- playerの先頭10件表示 ---
print("\n=== First 10 rows from player ===")
cur.execute("SELECT * FROM player LIMIT 10;")
for row in cur.fetchall():
    print(row)

cur.close()
conn.close()

=== Tables ===
character
player

=== Columns in character ===
character_id (INTEGER)
player_id (INTEGER)
character_name (VARCHAR(20))
HP (INTEGER)
MP (INTEGER)
EXP (INTEGER)

=== Columns in player ===
player_id (INTEGER)
fname (VARCHAR(20))
lname (VARCHAR(20))
points (INTEGER)
rank (VARCHAR(1))

=== First 10 rows from player ===
(0, 'yxAHc', 'vgoYy', 46, 'K')
(1, 'TipsN', 'roJsR', 14, 'Y')
(2, 'wZcEb', 'Gzuft', 60, 'S')
(3, 'FCrab', 'eqdqM', 25, 'A')
(4, 'DHgFg', 'Eseuu', 20, 'A')
(5, 'kBvez', 'yCvQS', 14, 'C')
(6, 'kNVep', 'SLtSC', 20, 'T')
(7, 'YNNWa', 'cmcBL', 29, 'Y')
(8, 'mtVcp', 'JPvuF', 92, 'C')
(9, 'EfxiD', 'IVljs', 61, 'S')